bagmati/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from news.views import IndexView,MessageViewHome
from django.views.generic import TemplateView
from exceptionsapp.views import error_404,error_500,error_403,error_400

handler404 = 'exceptionsapp.views.error_404'
handler403 = 'exceptionsapp.views.error_403'
handler400 = 'exceptionsapp.views.error_400'
handler400 = 'exceptionsapp.views.error_500'


urlpatterns = [
    path("", include("contracts.urls")),
    path("user/", include("users.urls")),
    path("", include("news.urls")),
    path("", include("company.urls")),
    path("", include("construction.urls")),
    path("", include("dam.urls")),
    path("", include("damknowledge.urls")),

    # home
    path("", IndexView.as_view(), name="index"),
    path('message/<slug:slug>/', MessageViewHome.as_view(), name='message'),
    #list of apps
    path('admin/', admin.site.urls),
    path("", include('django.contrib.auth.urls')),
    #external package
    path('ckeditor/', include('ckeditor_uploader.urls')),


    
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contracts/urls.py
from django.urls import path
from .views import *

app_name = "contracts"

urlpatterns = [
    # get list of contract or single contract
    path("contracts/completed/", ContractCompletedView.as_view(), name="contract"),
    path("contracts/ongoing/", ContractOngoingView.as_view(), name="contract=ongoing"),
    path(
        "contracts/progress/", ContractProgressView.as_view(), name="contract-progress"
    ),
    path("contracts/<int:pk>", ContractCompletedView.as_view(), name="contract"),
    # ----------static url----------------
    path("contracts-ongoing/", ClientContractOngoingView.as_view(), name="c-ongoing"),
    path("contracts-completed/", ClientContractCompletedView.as_view(), name="c-completed"),
    path("contracts-progress/", ClientContractProgressView.as_view(), name="c-progress"),
    # ----------static url----------------
    # add and update of contract
    # path("contract/add", ContractCreateView.as_view(), name="contract-add"),
    path("contract/add", addContract, name="contract-add"),
    path("contract/<int:pk>", ContractDetailView.as_view(), name="contract-detail"),
    path("contract-list/", ContractListView.as_view(), name="contract-list"),
    path(
        "contract/update/<int:pk>", ContractUpdateView.as_view(), name="contract-update"
    ),
    path(
        "contract/delete/<int:pk>", ContractDeleteView.as_view(), name="contract-delete"
    ),
    # add and update of contract detail
    path("contract-detail/", ContractDetailList.as_view(), name="contract-detail-list"),
    path(
        "contract/<int:pk>",
        ContractDetailDetailView.as_view(),
        name="contract-detail-detail",
    ),
    path(
        "contract-detail/add", ContractDetailAdd.as_view(), name="contract-detail-add"
    ),
    path(
        "contract-detail/<int:pk>/update",
        ContractDetailUpdate.as_view(),
        name="contract-detail-update",
    ),
    path(
        "contract-detail/<int:pk>/delete",
        ContractDetailDelete.as_view(),
        name="contract-detail-delete",
    ),
    # crud for contract Feature
    path("contract-feature/", ContractFeatureList.as_view(), name="contract-feature"),
    path(
        "contract-feature/<int:pk>",
        ContractFeatureDetail.as_view(),
        name="contract-feature-detail",
    ),
    path(
        "contract-feature/add",
        ContractFeatureCreate.as_view(),
        name="contract-feature-add",
    ),
    path(
        "contract-feature/<int:pk>/update",
        ContractFeatureUpdate.as_view(),
        name="contract-feature-update",
    ),
    path(
        "contract-feature/<int:pk>/delete",
        ContractFeatureUpdate.as_view(),
        name="contract-feature-delete",
    ),
    # Crud for Contract Progress
    path("contract-progress/", ContractProgressGet.as_view(), name="contract-progress"),
    path(
        "contract-progress/add",
        ContractProgressAdd.as_view(),
        name="contract-progress-add",
    ),
    path(
        "contract-progress/<int:pk>/update",
        ContractProgressUpdate.as_view(),
        name="contract-progress-update",
    ),
    path(
        "contract-progress/<int:pk>/delete",
        ContractProgressDelete.as_view(),
        name="contract-progress-delete",
    ),
    # get url of different contract elements
    path(
        "contract/<int:pk>/intro",
        ContractIntroductionView.as_view(),
        name="contract-intro",
    ),
    path(
        "contract/<int:pk>/feature",
        ContractFeatureView.as_view(),
        name="contract-feature",
    ),
    path(
        "contract/<int:pk>/location",
        ContractLocationView.as_view(),
        name="contract-location",
    ),
    path(
        "contract/<int:pk>/design-quality",
        ContractDesignQualityView.as_view(),
        name="contract-design-quality",
    ),
    path(
        "contract/<int:pk>/env-aspects",
        ContractEnviromentalAspects.as_view(),
        name="contract-env-aspects",
    ),
    # for displaying purposes only
    path("dhap-dam/", DhapdamView.as_view(), name="dhap-dam"),
    path("dhap-features/", DhapFeaturesView.as_view(), name="dhap-features"),
    path("dhap-location/", DhapLocationView.as_view(), name="dhap-location"),
    path(
        "dhap-work-components/",
        DhapWorkComponentsView.as_view(),
        name="dhap-work-components",
    ),
    path(
        "dhap-work-components/<int:pk>/",
        DhapWorkComponentsDetailView.as_view(),
        name="dhap-work-components-detail",
    ),
    path("dhap-contract/", DhapContractDetailView.as_view(), name="dhap-contract"),
    path("dhap-design/", DhapDesignView.as_view(), name="dhap-design"),
    path(
        "dhap-environmental/",
        DhapEnvironmentalView.as_view(),
        name="dhap-environmental",
    ),
    path("dhap-maps/", DhapMapsView.as_view(), name="dhap-maps"),
]

dam/urls.py
from django.urls import path
from .views import *

app_name = "dam"

urlpatterns = [    
    #---------------------dhap-dam----------------------
    #introduction
    path("admin/dhapdam/introduction", DhapIntroView.as_view(), name="dadmin-intro"),
    path("admin/dhapdam/introduction/create/", AddDhapIntroCreateView.as_view(), name="add-dhap-intro"),
    path("admin/dhapdam/introduction/<int:pk>/update",
        DhapIntroUpdateView.as_view(),
        name="dhap-intro-update",
    ),
    path("admin/dhapdam/introduction/<int:pk>/delete",
        DhapIntroDeleteView.as_view(),
        name="dhap-intro-delete",
    ),

    #features
    path("admin/dhapdam/features", DhapFeaturesView.as_view(), name="dadmin-features"),
    # add featute
    path("admin/dhapdam/add-features", DhapAddFeatures.as_view(), name="dadmin-add-features"),
    #edit feature
    path("admin/dhapdam/edit-features/<int:pk>/", DhapEditFeatures.as_view(), name="dadmin-edit-features"),
    
    # path(
    #     "contract-progress/<int:pk>/delete",
    #     ContractProgressDelete.as_view(),
    #     name="contract-progress-delete",
    # ),

    #location  and accessibility
    path("admin/dhapdam/location", DhapLocationView.as_view(), name="dadmin-location"),
    path("admin/dhapdam/location/create/", DhapLocationCreateView.as_view(), name="add-dhap-location"),
    path("admin/dhapdam/location/<int:pk>/update",
        DhapLocationUpdateView.as_view(),
        name="dhap-location-update",
    ),
    # path("admin/dhapdam/location/<int:pk>/delete",
    #     DhapIntroDeleteView.as_view(),
    #     name="dhap-location-delete",
    # ),

    #work components
    path("admin/dhapdam/work-components", DhapWorkComponentView.as_view(), name="dadmin-work-components"),
    path("admin/dhapdam/work-components/create/", DhapWorkComponentCreateView.as_view(), name="add-dhap-work-components"),
    path("admin/dhapdam/work-components/<int:pk>/update",
        DhapWorkComponentUpdateView.as_view(),
        name="dhap-work-components-update",
    ),
    path("admin/dhapdam/work-components/<int:pk>/delete",
        DhapWorkComponentDeleteView.as_view(),
        name="dhapwork-components-delete",
    ),
    # sub work component
    path("admin/dhapdam/sub-work-components", DhapSubWorkComponentView.as_view(), name="dadmin-sub-subwork"),
    path("admin/dhapdam/sub-work-components/create/", DhapSubWorkComponentCreateView.as_view(), name="add-dhap-subwork-components"),
    path("admin/dhapdam/sub-work-components/<int:pk>/update",
        DhapSubWorkComponentUpdateView.as_view(),
        name="dhap-subwork-components-update",
    ),
    path("admin/dhapdam/sub-work-components/<int:pk>/delete",
        DhapSubWorkComponentDeleteView.as_view(),
        name="dhap-subwork-components-delete",
    ),
    # contract
    path("admin/dhapdam/contract-detail", DhapContractDetailView.as_view(), name="dadmin-contract-detail"),
     # add detail
    path("admin/dhapdam/add-detail", DhapAddContractDetail.as_view(), name="dadmin-add-detail"),
    #edit detail
    path("admin/dhapdam/edit-detail<int:pk>/", DhapEditContractDetail.as_view(), name="dadmin-edit-detail"),

    #design and quality aspects
    path("admin/dhapdam/design-quality", DhapDesignQualityView.as_view(), name="dadmin-design-quality"),
    path("admin/dhapdam/design-quality/add/", DhapDesignQualityCreateView.as_view(), name="add-dadmin-design-quality"),
    path("admin/dhapdam/design-quality/edit/<int:pk>/",
        DhapDesignQualityUpdateView.as_view(),
        name="dadmin-design-quality-update",
    ),



    # sub design
    path("admin/dhapdam/sub-design-quality", DhapSubDesignQualityView.as_view(), name="dadmin-sub-design-quality"),
    path("admin/dhapdam/sub-design-quality/create/", DhapSubDesignQualityCreateView.as_view(), name="add-dadmin-sub-design-quality"),
    path("admin/dhapdam/sub-design-quality/<int:pk>/update",
        DhapSubDesignQualityUpdateView.as_view(),
        name="dadmin-design-sub-quality-update",
    ),
    path("admin/dhapdam/sub-design-quality/<int:pk>/delete",
        DhapSubDesignQualityDeleteView.as_view(),
        name="dadmin-design-sub-quality-delete",
    ),
    # path("admin/dhapdam/list-design-quality", DhapListDesignQualityView.as_view(), name="dadmin-list-design"),

    path("admin/dhapdam/environmental-aspects", DhapEnvironmentalAspectsView.as_view(), name="dadmin-environmental-aspects"),
    path("admin/dhapdam/environmental-aspects/add/", DhapEnvironmentalAspectsCreateView.as_view(), name="add-dadmin-environmental-aspects"),
    path("admin/dhapdam/environmental-aspects/edit",
        DhapEnvironmentalAspectsUpdateView.as_view(),
        name="dadmin-environmental-aspects-update",
    ),
    #maps
    path("admin/dhapdam/maps", DhapMapsView.as_view(), name="dadmin-maps"),
    path("admin/dhapdam/maps/create/", MapsCreateView.as_view(), name="add-maps"),
    path("admin/dhapdam/maps/<int:pk>/update",
        MapsUpdateView.as_view(),
        name="maps-update",
    ),
    path("admin/dhapdam/maps/<int:pk>/delete",
        MapsDeleteView.as_view(),
        name="maps-delete",
    ),
    

    #-------------------nagmati dam-------------------
    #introduction
    path("admin/nagmati/introduction", NagmatiIntroView.as_view(), name="nadmin-intro"),
    path("admin/nagmati/introduction/create/", AddNagmatiIntroCreateView.as_view(), name="add-nagmati-intro"),
    path("admin/nagmati/introduction/<int:pk>/update",
        NagmatiIntroUpdateView.as_view(),
        name="nagmati-intro-update",
    ),
    #location
    path("admin/nagmati/location", NagmatiLocationView.as_view(), name="nadmin-location"),  
    path("admin/nagmati/location/create/", NagmatiLocationCreateView.as_view(), name="add-nagmati-location"),
    path("admin/nagmati/location/<int:pk>/update",
        NagmatiLocationUpdateView.as_view(),
        name="nagmati-location-update",
    ),
    #status of project
    path("admin/nagmati/project-status", NagmatiProjectStatusView.as_view(), name="nadmin-project-status"),
    path("admin/dhapdam/project-status/create/", NagmatiProjectStatusCreateView.as_view(), name="add-nadmin-project-status"),
    path("admin/dhapdam/project-status/<int:pk>/update",
        NagmatiProjectStatusUpdateView.as_view(),
        name="nadmin-project-statusupdate",
    ),
    #maps
    path("admin/nagmati/maps", NagmatiMapsView.as_view(), name="nadmin-maps"),
    path("admin/nagmati/maps/create/", NagmatiMapsCreateView.as_view(), name="add-nagmati-maps"),
    path("admin/nagmati/maps/<int:pk>/update",
        NagmatiMapsUpdateView.as_view(),
        name="maps-nagmati-update",
    ),
    path("admin/nagmati/maps/<int:pk>/delete",
        NagmatiMapsDeleteView.as_view(),
        name="maps-nagmati-delete",
    ),
    
    #salient features
    path("admin/nagmati/features", NagmatiFeaturesView.as_view(), name="nadmin-features"),
     # add featute
    path("admin/nagmati/add-features", NagmatiAddFeatures.as_view(), name="nadmin-add-features"),
    #edit feature
    path("admin/nagmati/edit-features/<int:pk>/", NagmatiEditFeatures.as_view(), name="nadmin-edit-features"),
    
    
]

templates/dhapdam/dhap-comp.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %}Dhap Dam{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a href="{% url 'contracts:dhap-work-components' %}" class="link text-theme-light-blue">Dhap Dam / Work Components</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h5 class="content-title">Major Work Components</h5>
                <ul class="about__content---list">
                     <li class="nested">
                        <a data-toggle="collapse" href="#md" role="button">Main Dam</a>
                        <div class="collapse" id="md">
                            <ol class="about__content---list">
                            {% for work_com in work_components_main_dam %}
                                <li><a href="{% url 'contracts:dhap-work-components-detail' work_com.id %}" class="link text-theme-blue" target="_blank">{{work_com.title}}</a></li>
                            {% endfor %}

                        </ol>
                        </div>
                    </li>
                    <li class="nested">
                        <a data-toggle="collapse" href="#sd" role="button">Saddle Dam</a>
                        <div class="collapse" id="sd">
                            <ol class="about__content---list">
                                {% for work_com in work_components_saddle_dam %}
                                    <li><a href="{% url 'contracts:dhap-work-components-detail' work_com.id %}" class="link text-theme-blue" target="_blank">{{work_com.title}}</a></li>
                                {% endfor %}

                            </ol>
                        </div>
                    </li>
                </ul>
                {% comment %} {% for item in work_components %}
                <h5 class="content-title">Major Work Components</h5>
                <div class="about__content">
                    <ul class="about__content---list">
                        <li class="nested">
                            {{ item.title|safe }}
                            {% if item.sub_major_work_components %}
                                {% for i in item.sub_major_work_components.all %}
                                    <ul class="about__content---list">
                                        <li class="sub-nested">{{i.title}}</li>
                                    </ul>
                                {% endfor %}
                            {% endif %}
                        </li>
                    </ul>
                </div>
                <div class="about__image">
                    {% if item.image %}<img src="{{item.image.url}}" class="img-fluid" alt="">{% endif %}
                </div>
                {% endfor %} {% endcomment %}
            </div>
            

            <div class="col-md-4 col-sm-12">
                <div class="sidebar-tab sidebar-sticky-top">
                    <h5 class="sidebar-tab__title">Dham Dam</h5>
                    <ul class="sidebar-bar">
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-dam' %}" class="sidebar-bar__item---link">Introduction</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-features' %}" class="sidebar-bar__item---link">Salient features of Dam</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-location' %}" class="sidebar-bar__item---link">Location and Accessibility</a></li>
                        <li class="sidebar-bar__item active"><a href="{% url 'contracts:dhap-work-components' %}" class="sidebar-bar__item---link active">Major Work Components</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-contract' %}" class="sidebar-bar__item---link">Contract Details</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-design' %}" class="sidebar-bar__item---link">Design and Quality Aspects</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-environmental' %}" class="sidebar-bar__item---link">Environmental Aspects</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-maps' %}" class="sidebar-bar__item---link">Dhap Dam Maps</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/dhapdam/dhap-contract.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %}Dhap Dam{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a href="{% url 'contracts:dhap-contract' %}" class="link text-theme-light-blue">Dhap Dam / Contract Details</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h5 class="content-title">Contract Details</h5>
                <div class="about__content">
                    <p class="about__content---para">
                        {{contract_details.content}}
                    </p>
                </div>
                <div class="table-responsive bsa-responsive-table mt-3 border-0">
                    <table class="table table-bordered bsa-table">
                        <tbody>
                            <tr style="background-color: #d5e6ff">
                                <th style="text-align: left;">S.N.</th>
                                <th style="text-align: left;">Item</th>
                                <th style="text-align: left;">Detail</th>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>Name of Work</td>
                                <td>{{contract_details.Name_of_work}}</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Client</td>
                                <td>{{contract_details.client}}</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>Contract No.</td>
                                <td>{{contract_details.contract_no}}</td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>Name of Contractor</td>
                                <td>{{contract_details.name_of_contractor}}</td>
                            </tr>
                            <tr>
                                <td>5</td>
                                <td>Date of Agreement </td>
                                <td>{{contract_details.date_of_agreement}}</td>
                            </tr>
                            <tr>
                                <td>6</td>
                                <td>Initial Date of Completion (DOC)</td>
                                <td>{{contract_details.intial_date_of_completion}}</td>
                            </tr>
                            <tr>
                                <td>7</td>
                                <td>Revised Date of Completion</td>
                                <td>{{contract_details.revised_date_of_completion}}</td>

                            </tr>
                            <tr>
                                <td>8</td>
                                <td>Contract Amount with VAT</td>
                                <td>{{contract_details.contract_amount_with_VAT}}</td>

                            </tr>
                            <tr>
                                <td>9</td>
                                <td>Physical Progress Till</td>
                                <td>{{contract_details.physical_progress}}</td>

                            </tr>
                            <tr>
                                <td>10</td>
                                <td>Financial Progress Till</td>
                                <td>{{contract_details.financial_progress}}</td>

                            </tr>
                            <tr>
                                <td>11</td>
                                <td>Authorized/Responsible Person</td>
                                <td>{{contract_details.responsible_person}}</td>

                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sidebar-tab sidebar-sticky-top">
                    <h5 class="sidebar-tab__title">Dham Dam</h5>
                    <ul class="sidebar-bar">
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-dam' %}" class="sidebar-bar__item---link">Introduction</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-features' %}" class="sidebar-bar__item---link">Salient features of Dam</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-location' %}" class="sidebar-bar__item---link">Location and Accessibility</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-work-components' %}" class="sidebar-bar__item---link">Major Work Components</a></li>
                        <li class="sidebar-bar__item active"><a href="{% url 'contracts:dhap-contract' %}" class="sidebar-bar__item---link active">Contract Details</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-design' %}" class="sidebar-bar__item---link">Design and Quality Aspects</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-environmental' %}" class="sidebar-bar__item---link">Environmental Aspects</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-maps' %}" class="sidebar-bar__item---link">Dhap Dam Maps</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/dhapdam/dhap-env.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %}Dhap Dam{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a href="{% url 'contracts:dhap-environmental' %}" class="link text-theme-light-blue">Dhap Dam / Environmental Aspects</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">

            {% if environmental_aspects %}
                <h5 class="content-title">Environmental Aspects</h5>
            {% endif  %}
                <div class="about__content">
                    <p class="about__content---para">
                        {{environmental_aspects.content}}
                    </p>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sidebar-tab sidebar-sticky-top">
                    <h5 class="sidebar-tab__title">Dham Dam</h5>
                    <ul class="sidebar-bar">
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-dam' %}" class="sidebar-bar__item---link">Introduction</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-features' %}" class="sidebar-bar__item---link">Salient features of Dam</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-location' %}" class="sidebar-bar__item---link">Location and Accessibility</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-work-components' %}" class="sidebar-bar__item---link">Major Work Components</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-contract' %}" class="sidebar-bar__item---link">Contract Details</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-design' %}" class="sidebar-bar__item---link">Design and Quality Aspects</a></li>
                        <li class="sidebar-bar__item active"><a href="{% url 'contracts:dhap-environmental' %}" class="sidebar-bar__item---link active">Environmental Aspects</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-maps' %}" class="sidebar-bar__item---link">Dhap Dam Maps</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/dhapdam/dhap-location.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- css -->
{% block static %}
<link rel="stylesheet" href="{% static 'css/venobox.min.css' %}"> {% endblock %}
<!-- title -->
{% block title %}Dhap Dam{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a href="{% url 'contracts:dhap-location' %}" class="link text-theme-light-blue">Dhap Dam / Location & Accessibility</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h5 class="content-title">Location and Accessibility</h5>
                <div class="about__content">
                    <p>
                        {{location.content|safe}}
                    </p>
                    {% if location.image %}
                    <div class="about__image">
                        <a href="{{location.image.url}}" class="venobox" data-gall="gallery-item">
                            <img src="{{location.image.url}}" alt="" class="img-fluid">
                        </a>
                    </div>
                    {% endif %}

                </div>
                <div class="row">
                    {% if location.accessibility_content %}
                    <div class="col-12">
                        <div class="about__content">
                            <h6>Accessibility</h6>
                            <p>
                                {% if location.accessibility_content %}{{location.accessibility_content|safe}}{% endif %}

                            </p>
                            {% if location.accessibility_image %}
                            <div class="about__image">
                                <a href="{{location.accessibility_image.url}}" class="venobox" data-gall="gallery-item">
                                    <img src="{{location.accessibility_image.url}}" alt="" class="img-fluid">
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sidebar-tab sidebar-sticky-top">
                    <h5 class="sidebar-tab__title">Dham Dam</h5>
                    <ul class="sidebar-bar">
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-dam' %}" class="sidebar-bar__item---link">Introduction</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-features' %}" class="sidebar-bar__item---link">Salient features of Dam</a></li>
                        <li class="sidebar-bar__item active"><a href="{% url 'contracts:dhap-location' %}" class="sidebar-bar__item---link active">Location and Accessibility</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-work-components' %}" class="sidebar-bar__item---link">Major Work Components</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-contract' %}" class="sidebar-bar__item---link">Contract Details</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-design' %}" class="sidebar-bar__item---link">Design and Quality Aspects</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-environmental' %}" class="sidebar-bar__item---link">Environmental Aspects</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:dhap-maps' %}" class="sidebar-bar__item---link">Dhap Dam Maps</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %} } {% block script %}
<script src="{% static 'js/venobox.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $('.venobox').venobox();
    });
</script>
{% endblock %}