bagmati/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from news.views import IndexView,MessageViewHome
from django.views.generic import TemplateView
from exceptionsapp.views import error_404,error_500,error_403,error_400

handler404 = 'exceptionsapp.views.error_404'
handler403 = 'exceptionsapp.views.error_403'
handler400 = 'exceptionsapp.views.error_400'
handler400 = 'exceptionsapp.views.error_500'


urlpatterns = [
    path("", include("contracts.urls")),
    path("user/", include("users.urls")),
    path("", include("news.urls")),
    path("", include("company.urls")),
    path("", include("construction.urls")),
    path("", include("dam.urls")),
    path("", include("damknowledge.urls")),

    # home
    path("", IndexView.as_view(), name="index"),
    path('message/<slug:slug>/', MessageViewHome.as_view(), name='message'),
    #list of apps
    path('admin/', admin.site.urls),
    path("", include('django.contrib.auth.urls')),
    #external package
    path('ckeditor/', include('ckeditor_uploader.urls')),


    
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dam/urls.py
from django.urls import path
from .views import *

app_name = "dam"

urlpatterns = [    
    #---------------------dhap-dam----------------------
    #introduction
    path("admin/dhapdam/introduction", DhapIntroView.as_view(), name="dadmin-intro"),
    path("admin/dhapdam/introduction/create/", AddDhapIntroCreateView.as_view(), name="add-dhap-intro"),
    path("admin/dhapdam/introduction/<int:pk>/update",
        DhapIntroUpdateView.as_view(),
        name="dhap-intro-update",
    ),
    path("admin/dhapdam/introduction/<int:pk>/delete",
        DhapIntroDeleteView.as_view(),
        name="dhap-intro-delete",
    ),

    #features
    path("admin/dhapdam/features", DhapFeaturesView.as_view(), name="dadmin-features"),
    # add featute
    path("admin/dhapdam/add-features", DhapAddFeatures.as_view(), name="dadmin-add-features"),
    #edit feature
    path("admin/dhapdam/edit-features/<int:pk>/", DhapEditFeatures.as_view(), name="dadmin-edit-features"),
    
    # path(
    #     "contract-progress/<int:pk>/delete",
    #     ContractProgressDelete.as_view(),
    #     name="contract-progress-delete",
    # ),

    #location  and accessibility
    path("admin/dhapdam/location", DhapLocationView.as_view(), name="dadmin-location"),
    path("admin/dhapdam/location/create/", DhapLocationCreateView.as_view(), name="add-dhap-location"),
    path("admin/dhapdam/location/<int:pk>/update",
        DhapLocationUpdateView.as_view(),
        name="dhap-location-update",
    ),
    # path("admin/dhapdam/location/<int:pk>/delete",
    #     DhapIntroDeleteView.as_view(),
    #     name="dhap-location-delete",
    # ),

    #work components
    path("admin/dhapdam/work-components", DhapWorkComponentView.as_view(), name="dadmin-work-components"),
    path("admin/dhapdam/work-components/create/", DhapWorkComponentCreateView.as_view(), name="add-dhap-work-components"),
    path("admin/dhapdam/work-components/<int:pk>/update",
        DhapWorkComponentUpdateView.as_view(),
        name="dhap-work-components-update",
    ),
    path("admin/dhapdam/work-components/<int:pk>/delete",
        DhapWorkComponentDeleteView.as_view(),
        name="dhapwork-components-delete",
    ),
    # sub work component
    path("admin/dhapdam/sub-work-components", DhapSubWorkComponentView.as_view(), name="dadmin-sub-subwork"),
    path("admin/dhapdam/sub-work-components/create/", DhapSubWorkComponentCreateView.as_view(), name="add-dhap-subwork-components"),
    path("admin/dhapdam/sub-work-components/<int:pk>/update",
        DhapSubWorkComponentUpdateView.as_view(),
        name="dhap-subwork-components-update",
    ),
    path("admin/dhapdam/sub-work-components/<int:pk>/delete",
        DhapSubWorkComponentDeleteView.as_view(),
        name="dhap-subwork-components-delete",
    ),
    # contract
    path("admin/dhapdam/contract-detail", DhapContractDetailView.as_view(), name="dadmin-contract-detail"),
     # add detail
    path("admin/dhapdam/add-detail", DhapAddContractDetail.as_view(), name="dadmin-add-detail"),
    #edit detail
    path("admin/dhapdam/edit-detail<int:pk>/", DhapEditContractDetail.as_view(), name="dadmin-edit-detail"),

    #design and quality aspects
    path("admin/dhapdam/design-quality", DhapDesignQualityView.as_view(), name="dadmin-design-quality"),
    path("admin/dhapdam/design-quality/add/", DhapDesignQualityCreateView.as_view(), name="add-dadmin-design-quality"),
    path("admin/dhapdam/design-quality/edit/<int:pk>/",
        DhapDesignQualityUpdateView.as_view(),
        name="dadmin-design-quality-update",
    ),



    # sub design
    path("admin/dhapdam/sub-design-quality", DhapSubDesignQualityView.as_view(), name="dadmin-sub-design-quality"),
    path("admin/dhapdam/sub-design-quality/create/", DhapSubDesignQualityCreateView.as_view(), name="add-dadmin-sub-design-quality"),
    path("admin/dhapdam/sub-design-quality/<int:pk>/update",
        DhapSubDesignQualityUpdateView.as_view(),
        name="dadmin-design-sub-quality-update",
    ),
    path("admin/dhapdam/sub-design-quality/<int:pk>/delete",
        DhapSubDesignQualityDeleteView.as_view(),
        name="dadmin-design-sub-quality-delete",
    ),
    # path("admin/dhapdam/list-design-quality", DhapListDesignQualityView.as_view(), name="dadmin-list-design"),

    path("admin/dhapdam/environmental-aspects", DhapEnvironmentalAspectsView.as_view(), name="dadmin-environmental-aspects"),
    path("admin/dhapdam/environmental-aspects/add/", DhapEnvironmentalAspectsCreateView.as_view(), name="add-dadmin-environmental-aspects"),
    path("admin/dhapdam/environmental-aspects/edit",
        DhapEnvironmentalAspectsUpdateView.as_view(),
        name="dadmin-environmental-aspects-update",
    ),
    #maps
    path("admin/dhapdam/maps", DhapMapsView.as_view(), name="dadmin-maps"),
    path("admin/dhapdam/maps/create/", MapsCreateView.as_view(), name="add-maps"),
    path("admin/dhapdam/maps/<int:pk>/update",
        MapsUpdateView.as_view(),
        name="maps-update",
    ),
    path("admin/dhapdam/maps/<int:pk>/delete",
        MapsDeleteView.as_view(),
        name="maps-delete",
    ),
    

    #-------------------nagmati dam-------------------
    #introduction
    path("admin/nagmati/introduction", NagmatiIntroView.as_view(), name="nadmin-intro"),
    path("admin/nagmati/introduction/create/", AddNagmatiIntroCreateView.as_view(), name="add-nagmati-intro"),
    path("admin/nagmati/introduction/<int:pk>/update",
        NagmatiIntroUpdateView.as_view(),
        name="nagmati-intro-update",
    ),
    #location
    path("admin/nagmati/location", NagmatiLocationView.as_view(), name="nadmin-location"),  
    path("admin/nagmati/location/create/", NagmatiLocationCreateView.as_view(), name="add-nagmati-location"),
    path("admin/nagmati/location/<int:pk>/update",
        NagmatiLocationUpdateView.as_view(),
        name="nagmati-location-update",
    ),
    #status of project
    path("admin/nagmati/project-status", NagmatiProjectStatusView.as_view(), name="nadmin-project-status"),
    path("admin/dhapdam/project-status/create/", NagmatiProjectStatusCreateView.as_view(), name="add-nadmin-project-status"),
    path("admin/dhapdam/project-status/<int:pk>/update",
        NagmatiProjectStatusUpdateView.as_view(),
        name="nadmin-project-statusupdate",
    ),
    #maps
    path("admin/nagmati/maps", NagmatiMapsView.as_view(), name="nadmin-maps"),
    path("admin/nagmati/maps/create/", NagmatiMapsCreateView.as_view(), name="add-nagmati-maps"),
    path("admin/nagmati/maps/<int:pk>/update",
        NagmatiMapsUpdateView.as_view(),
        name="maps-nagmati-update",
    ),
    path("admin/nagmati/maps/<int:pk>/delete",
        NagmatiMapsDeleteView.as_view(),
        name="maps-nagmati-delete",
    ),
    
    #salient features
    path("admin/nagmati/features", NagmatiFeaturesView.as_view(), name="nadmin-features"),
     # add featute
    path("admin/nagmati/add-features", NagmatiAddFeatures.as_view(), name="nadmin-add-features"),
    #edit feature
    path("admin/nagmati/edit-features/<int:pk>/", NagmatiEditFeatures.as_view(), name="nadmin-edit-features"),
    
    
]

users/urls.py
from django.urls import path
from .views import (
    LoginView,
    register_view,
    logout_view,
    EmployeeDetailView,
    ExEmployeeView,
    ExProjectheadView,
    admin_profiles,
    ForgotPasswordView,
    ResetPasswordView,
    AdminProfileView,
    AdminProfileEditView,
    AdminImageEditView,
    change_password,
)
from django.contrib.auth import views as auth_views
from .views import (
    PasswordResetDoneView,
    PasswordResetView,
    PasswordResetConfirmView,
    UserPasswordResetConfirmView,
    redirect_view,
)


app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("redirect/user/", redirect_view, name="logout-user"),

    path("register/", register_view, name="register"),
    path("employee-detail/", EmployeeDetailView.as_view(), name="employee-detail"),
    path("ex-employee/", ExEmployeeView.as_view(), name="ex-employee"),
    path("ex-projecthead/", ExProjectheadView.as_view(), name="ex-projecthead"),
    # admin profile
    path("admin/profile/", AdminProfileView.as_view(), name="admin-profile"),
    path(
        "edit/profile/<int:pk>/",
        AdminProfileEditView.as_view(),
        name="admin-profile-edit",
    ),
    # path("edit/image/<int:pk>/", AdminImageEditView.as_view(), name="admin-image-edit"),
    # admin profile
    path("admin-profiles/", admin_profiles, name="admin-profile"),
    # change password
    path("change-password/", change_password, name="change_passwords"),
    # forgot password
    # 1st step
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="registration/forgot-password.html",
            subject_template_name="registration/forgot_password/password_reset_subject.txt",
            html_email_template_name="registration/forgot_password/password_reset_email.html"
            # success_url='/login/'
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    # path(
    #     "password-reset-confirm/<uidb64>/<token>/",
    #     PasswordResetConfirmView.as_view(
    #         template_name="registration/reset-password.html"
    #     ),
    #     name="password_reset_confirm",
    # ),
    path(
        "passwords-reset-confirm/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/login.html"
        ),
        name="password_reset_complete",
    ),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("reset-password/", ResetPasswordView.as_view(), name="reset-password"),
]

templates/aboutus/about.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %} About Us{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a
                    href="{% url 'company:about' %}" class="link text-theme-light-blue">Introduction</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h5 class="content-title">Introduction</h5>
                <div class="content-wrap">
                    <div class="about__content">
                        {% if introduction %}
                        <p class="about__content---para img-para">
                            <!-- content -->
                            {% if introduction.image %}<img src="{{introduction.image.url}}" class="img-fluid d-none d-sm-none d-md-block" alt="" />{% endif %} {{introduction.content_upload|safe}}
                        </p>
                        {% else %}
                        <p>No data to display</p>
                        {% endif %}
                    </div>

                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sidebar-tab sidebar-sticky-top">
                    <h5 class="sidebar-tab__title">About Us</h5>
                    <ul class="sidebar-bar">
                        <li class="sidebar-bar__item active"><a href="{% url 'company:about' %}" class="sidebar-bar__item---link active">Introduction</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'company:structure' %}" class="sidebar-bar__item---link">Organization Structure</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'company:citizen-charter' %}" class="sidebar-bar__item---link">Citizen Charter</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'users:employee-detail' %}" class="sidebar-bar__item---link">Employee Details</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'users:ex-employee' %}" class="sidebar-bar__item---link">Ex Employess</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'users:ex-projecthead' %}" class="sidebar-bar__item---link">Ex Project Heads</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/aboutus/citchat.html
 {% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %}Citizen Charter{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a href="{% url 'company:citizen-charter' %}" class="link text-theme-light-blue">Citizen Charter</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h5 class="content-title">Citizen Charter</h5>
                <div class="row mt-3">
                    <div class="col-12">
                        <div class="cc-image">
                            <img src="{{citizen.file.url}}" class="img-fluid" alt="">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sidebar-tab sidebar-sticky-top">
                    <h5 class="sidebar-tab__title">About Us</h5>
                    <ul class="sidebar-bar">
                        <li class="sidebar-bar__item"><a href="{% url 'company:about' %}" class="sidebar-bar__item---link">Introduction</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'company:structure' %}" class="sidebar-bar__item---link">Organization Structure</a></li>
                        <li class="sidebar-bar__item active"><a href="{% url 'company:citizen-charter' %}" class="sidebar-bar__item---link active">Citizen Charter</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'users:employee-detail' %}" class="sidebar-bar__item---link">Employee Details</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'users:ex-employee' %}" class="sidebar-bar__item---link">Ex Employess</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'users:ex-projecthead' %}" class="sidebar-bar__item---link">Ex Project Heads</a></li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</section>
{% endblock %}

templates/aboutus/employee-detail.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- css -->
{% block static %}
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/custom-dataTables.css' %}"> {% endblock %}
<!-- title -->
{% block title %}Employee Detail{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a
                    href="{% url 'users:employee-detail' %}" class="link text-theme-light-blue">Employee
                    Detail</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h5 class="content-title">Employee Details</h5>
                <div class="row">
                    <div class="col-12">
                        <div class="p-3 table-responsive bsa-responsive-table">
                            <table id="table_dataframe" class="table" style="width:100%">
                                <thead>
                                    <tr>
                                        <th width="2%">SN</th>
                                        <th>Photo</th>
                                        <th>Name</th>
                                        <th>Designation</th>
                                        <th>Phone</th>
                                        <th>Email</th>
                                        <th>Temporary Address</th>
                                        <th>Permanent Address</th>
                                        <th>Join Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in employees %}
                                    <tr>
                                        <td class="text-center">{{forloop.counter}}</td>
                                        <td class="table-image">
                                            {% if item.image %}<img src="{{item.image.url}}" alt="" />{% else %}None{% endif %}
                                        </td>
                                        <td>{{item.full_name}}</td>
                                        <td>
                                            <span class="badge bg-info f-13 font-weight-400">{{item.designation}}</span
                                        >
                                      </td>
                                      <td>
                                        <span
                                          class="badge bg-theme-green f-13 font-weight-400 text-white"
                                          >{{item.phone}}</span
                                        >
                                      </td>
                                      <td>{% if item.email %}{{item.email}}{% else %}--{% endif %}</td>
                                      <td>{% if item.temporary_address %}{{item.temporary_address}}{% else %}--{% endif %}</td>
                                      <td>{% if item.permanent_address %}{{item.permanent_address}}{% else %}--{% endif %}</td>
                                      <td>
                                        {% if item.date_joined %}{{item.date_joined}}{% endif %}
                                      </td>
                                    </tr>
                                    {% endfor %}

                                  </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sidebar-tab sidebar-sticky-top">
                    <h5 class="sidebar-tab__title">About Us</h5>
                    <ul class="sidebar-bar">
                        <li class="sidebar-bar__item"><a href="{% url 'company:about' %}" class="sidebar-bar__item---link">Introduction</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'company:structure' %}" class="sidebar-bar__item---link">Organization Structure</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'company:citizen-charter' %}" class="sidebar-bar__item---link">Citizen Charter</a></li>
                        <li class="sidebar-bar__item active"><a href="{% url 'users:employee-detail' %}" class="sidebar-bar__item---link active">Employee Details</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'users:ex-employee' %}" class="sidebar-bar__item---link">Ex Employess</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'users:ex-projecthead' %}" class="sidebar-bar__item---link">Ex Project Heads</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %} {% block script %}
<script src="{% static 'admin/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
<script>
    $(document).ready(function() {
      $('#table_dataframe').DataTable({
            "scrollX": true
        });
    });
</script>
{% endblock %}

templates/aboutus/ex-employee.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- css -->
{% block static %}
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/custom-dataTables.css' %}"> {% endblock %}
<!-- title -->
{% block title %}Ex Employee{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a
                    href="{% url 'users:ex-employee' %}" class="link text-theme-light-blue">Ex Employee
                    Detail</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12 ">
                <h5 class="content-title">Ex Employee Details</h5>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive bsa-responsive-table p-3">

                            <table id="table_dataframe" class="table" style="width:100%">
                                <thead>
                                    <tr>
                                        <th width="2%">S.No</th>
                                        <th width="8%">Photo</th>
                                        <th width="18%">Name</th>
                                        <th width="15%">Designation</th>
                                        <th width="8%">Phone</th>
                                        <th width="12%">Email</th>
                                        <th width="15%">Temporary Address</th>
                                        <th width="15%">Permanment Address</th>
                                        <th width="12%">Join Date</th>
                                        <th width="12%">Leave Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for user in ex_employees %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        {% if user.image %}
                                        <td><img src="{{ user.image.url }}" alt="" width="80" class="img-fluid border">
                                        </td>{% endif %}
                                        <td>{{ user.full_name }}</td>
                                        <td><span class="badge bg-theme-light-blue f-13 font-weight-400">{% if user.designation %}{{ user.designation }}{% else %} None {% endif %}</span>
                                        </td>
                                        <td><span class="badge bg-theme-green f-13 font-weight-400">{{ user.phone }}</span>
                                        </td>
                                        <td>{% if user.email %}{{user.email}}{% else %}--{% endif %}</td>
                                        <td>{{user.temporary_address}}</td>
                                        <td>{{user.permanent_address}}</td>
                                        <td><span class="badge bg-secondary f-13 font-weight-400">{{ user.date_joined }}</span>
                                        </td>
                                        <td>
                                            <span class="badge bg-secondary f-14 font-weight-400">{% if user.leave_date %}{{user.leave_date}}{% else %}working{% endif %}</span>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-12 ">
                <div class="sidebar-tab sidebar-sticky-top">
                    <h5 class="sidebar-tab__title">About Us</h5>
                    <ul class="sidebar-bar">
                        <li class="sidebar-bar__item"><a href="{% url 'company:about' %}" class="sidebar-bar__item---link">Introduction</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'company:structure' %}" class="sidebar-bar__item---link">Organization Structure</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'company:citizen-charter' %}" class="sidebar-bar__item---link">Citizen Charter</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'users:employee-detail' %}" class="sidebar-bar__item---link">Employee Details</a></li>
                        <li class="sidebar-bar__item active"><a href="{% url 'users:ex-employee' %}" class="sidebar-bar__item---link active">Ex Employess</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'users:ex-projecthead' %}" class="sidebar-bar__item---link">Ex Project Heads</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %} {% block script %}
<script src="{% static 'admin/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#table_dataframe').DataTable({
            "scrollX": true
        });
    });
</script>
{% endblock %}

templates/aboutus/orgstr.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %}Organization Structure{% endblock %}
<!-- content -->
{% block content %}

<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a
                    href="{% url 'company:structure' %}" class="link text-theme-light-blue">Organization
                    Structure</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h5 class="content-title">Organization Structure</h5>
                <div class="row mt-3">
                    <div class="col-12">
                        {% if structure.file %}
                            <div class="os-image">
                                <img src="{{structure.file.url}}" class="img-fluid" alt="">
                                
                            </div>
                        {% else %}
                            <p>File not uploaded</p>
                        {% endif %}
                        

                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sidebar-tab sidebar-sticky-top">
                    <h5 class="sidebar-tab__title">About Us</h5>
                    <ul class="sidebar-bar">
                        <li class="sidebar-bar__item"><a href="{% url 'company:about' %}" class="sidebar-bar__item---link">Introduction</a></li>
                        <li class="sidebar-bar__item active"><a href=" {% url 'company:structure' %} " class="sidebar-bar__item---link active ">Organization Structure</a></li>
                        <li class="sidebar-bar__item "><a href="{% url 'company:citizen-charter' %} " class="sidebar-bar__item---link ">Citizen Charter</a></li>
                        <li class="sidebar-bar__item "><a href="{% url 'users:employee-detail' %} " class="sidebar-bar__item---link ">Employee Details</a></li>
                        <li class="sidebar-bar__item "><a href="{% url 'users:ex-employee' %} " class="sidebar-bar__item---link ">Ex Employess</a></li>
                        <li class="sidebar-bar__item "><a href="{% url 'users:ex-projecthead' %} " class="sidebar-bar__item---link ">Ex Project Heads</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}