bagmati/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from news.views import IndexView,MessageViewHome
from django.views.generic import TemplateView
from exceptionsapp.views import error_404,error_500,error_403,error_400

handler404 = 'exceptionsapp.views.error_404'
handler403 = 'exceptionsapp.views.error_403'
handler400 = 'exceptionsapp.views.error_400'
handler400 = 'exceptionsapp.views.error_500'


urlpatterns = [
    path("", include("contracts.urls")),
    path("user/", include("users.urls")),
    path("", include("news.urls")),
    path("", include("company.urls")),
    path("", include("construction.urls")),
    path("", include("dam.urls")),
    path("", include("damknowledge.urls")),

    # home
    path("", IndexView.as_view(), name="index"),
    path('message/<slug:slug>/', MessageViewHome.as_view(), name='message'),
    #list of apps
    path('admin/', admin.site.urls),
    path("", include('django.contrib.auth.urls')),
    #external package
    path('ckeditor/', include('ckeditor_uploader.urls')),


    
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dam/urls.py
from django.urls import path
from .views import *

app_name = "dam"

urlpatterns = [    
    #---------------------dhap-dam----------------------
    #introduction
    path("admin/dhapdam/introduction", DhapIntroView.as_view(), name="dadmin-intro"),
    path("admin/dhapdam/introduction/create/", AddDhapIntroCreateView.as_view(), name="add-dhap-intro"),
    path("admin/dhapdam/introduction/<int:pk>/update",
        DhapIntroUpdateView.as_view(),
        name="dhap-intro-update",
    ),
    path("admin/dhapdam/introduction/<int:pk>/delete",
        DhapIntroDeleteView.as_view(),
        name="dhap-intro-delete",
    ),

    #features
    path("admin/dhapdam/features", DhapFeaturesView.as_view(), name="dadmin-features"),
    # add featute
    path("admin/dhapdam/add-features", DhapAddFeatures.as_view(), name="dadmin-add-features"),
    #edit feature
    path("admin/dhapdam/edit-features/<int:pk>/", DhapEditFeatures.as_view(), name="dadmin-edit-features"),
    
    # path(
    #     "contract-progress/<int:pk>/delete",
    #     ContractProgressDelete.as_view(),
    #     name="contract-progress-delete",
    # ),

    #location  and accessibility
    path("admin/dhapdam/location", DhapLocationView.as_view(), name="dadmin-location"),
    path("admin/dhapdam/location/create/", DhapLocationCreateView.as_view(), name="add-dhap-location"),
    path("admin/dhapdam/location/<int:pk>/update",
        DhapLocationUpdateView.as_view(),
        name="dhap-location-update",
    ),
    # path("admin/dhapdam/location/<int:pk>/delete",
    #     DhapIntroDeleteView.as_view(),
    #     name="dhap-location-delete",
    # ),

    #work components
    path("admin/dhapdam/work-components", DhapWorkComponentView.as_view(), name="dadmin-work-components"),
    path("admin/dhapdam/work-components/create/", DhapWorkComponentCreateView.as_view(), name="add-dhap-work-components"),
    path("admin/dhapdam/work-components/<int:pk>/update",
        DhapWorkComponentUpdateView.as_view(),
        name="dhap-work-components-update",
    ),
    path("admin/dhapdam/work-components/<int:pk>/delete",
        DhapWorkComponentDeleteView.as_view(),
        name="dhapwork-components-delete",
    ),
    # sub work component
    path("admin/dhapdam/sub-work-components", DhapSubWorkComponentView.as_view(), name="dadmin-sub-subwork"),
    path("admin/dhapdam/sub-work-components/create/", DhapSubWorkComponentCreateView.as_view(), name="add-dhap-subwork-components"),
    path("admin/dhapdam/sub-work-components/<int:pk>/update",
        DhapSubWorkComponentUpdateView.as_view(),
        name="dhap-subwork-components-update",
    ),
    path("admin/dhapdam/sub-work-components/<int:pk>/delete",
        DhapSubWorkComponentDeleteView.as_view(),
        name="dhap-subwork-components-delete",
    ),
    # contract
    path("admin/dhapdam/contract-detail", DhapContractDetailView.as_view(), name="dadmin-contract-detail"),
     # add detail
    path("admin/dhapdam/add-detail", DhapAddContractDetail.as_view(), name="dadmin-add-detail"),
    #edit detail
    path("admin/dhapdam/edit-detail<int:pk>/", DhapEditContractDetail.as_view(), name="dadmin-edit-detail"),

    #design and quality aspects
    path("admin/dhapdam/design-quality", DhapDesignQualityView.as_view(), name="dadmin-design-quality"),
    path("admin/dhapdam/design-quality/add/", DhapDesignQualityCreateView.as_view(), name="add-dadmin-design-quality"),
    path("admin/dhapdam/design-quality/edit/<int:pk>/",
        DhapDesignQualityUpdateView.as_view(),
        name="dadmin-design-quality-update",
    ),



    # sub design
    path("admin/dhapdam/sub-design-quality", DhapSubDesignQualityView.as_view(), name="dadmin-sub-design-quality"),
    path("admin/dhapdam/sub-design-quality/create/", DhapSubDesignQualityCreateView.as_view(), name="add-dadmin-sub-design-quality"),
    path("admin/dhapdam/sub-design-quality/<int:pk>/update",
        DhapSubDesignQualityUpdateView.as_view(),
        name="dadmin-design-sub-quality-update",
    ),
    path("admin/dhapdam/sub-design-quality/<int:pk>/delete",
        DhapSubDesignQualityDeleteView.as_view(),
        name="dadmin-design-sub-quality-delete",
    ),
    # path("admin/dhapdam/list-design-quality", DhapListDesignQualityView.as_view(), name="dadmin-list-design"),

    path("admin/dhapdam/environmental-aspects", DhapEnvironmentalAspectsView.as_view(), name="dadmin-environmental-aspects"),
    path("admin/dhapdam/environmental-aspects/add/", DhapEnvironmentalAspectsCreateView.as_view(), name="add-dadmin-environmental-aspects"),
    path("admin/dhapdam/environmental-aspects/edit",
        DhapEnvironmentalAspectsUpdateView.as_view(),
        name="dadmin-environmental-aspects-update",
    ),
    #maps
    path("admin/dhapdam/maps", DhapMapsView.as_view(), name="dadmin-maps"),
    path("admin/dhapdam/maps/create/", MapsCreateView.as_view(), name="add-maps"),
    path("admin/dhapdam/maps/<int:pk>/update",
        MapsUpdateView.as_view(),
        name="maps-update",
    ),
    path("admin/dhapdam/maps/<int:pk>/delete",
        MapsDeleteView.as_view(),
        name="maps-delete",
    ),
    

    #-------------------nagmati dam-------------------
    #introduction
    path("admin/nagmati/introduction", NagmatiIntroView.as_view(), name="nadmin-intro"),
    path("admin/nagmati/introduction/create/", AddNagmatiIntroCreateView.as_view(), name="add-nagmati-intro"),
    path("admin/nagmati/introduction/<int:pk>/update",
        NagmatiIntroUpdateView.as_view(),
        name="nagmati-intro-update",
    ),
    #location
    path("admin/nagmati/location", NagmatiLocationView.as_view(), name="nadmin-location"),  
    path("admin/nagmati/location/create/", NagmatiLocationCreateView.as_view(), name="add-nagmati-location"),
    path("admin/nagmati/location/<int:pk>/update",
        NagmatiLocationUpdateView.as_view(),
        name="nagmati-location-update",
    ),
    #status of project
    path("admin/nagmati/project-status", NagmatiProjectStatusView.as_view(), name="nadmin-project-status"),
    path("admin/dhapdam/project-status/create/", NagmatiProjectStatusCreateView.as_view(), name="add-nadmin-project-status"),
    path("admin/dhapdam/project-status/<int:pk>/update",
        NagmatiProjectStatusUpdateView.as_view(),
        name="nadmin-project-statusupdate",
    ),
    #maps
    path("admin/nagmati/maps", NagmatiMapsView.as_view(), name="nadmin-maps"),
    path("admin/nagmati/maps/create/", NagmatiMapsCreateView.as_view(), name="add-nagmati-maps"),
    path("admin/nagmati/maps/<int:pk>/update",
        NagmatiMapsUpdateView.as_view(),
        name="maps-nagmati-update",
    ),
    path("admin/nagmati/maps/<int:pk>/delete",
        NagmatiMapsDeleteView.as_view(),
        name="maps-nagmati-delete",
    ),
    
    #salient features
    path("admin/nagmati/features", NagmatiFeaturesView.as_view(), name="nadmin-features"),
     # add featute
    path("admin/nagmati/add-features", NagmatiAddFeatures.as_view(), name="nadmin-add-features"),
    #edit feature
    path("admin/nagmati/edit-features/<int:pk>/", NagmatiEditFeatures.as_view(), name="nadmin-edit-features"),
    
    
]

news/urls.py
from django.urls import path
from .views import *

app_name = "news"
urlpatterns = [
    # path("news/", NewsView.as_view(), name="news"),
    path("news-detail/<int:pk>/", NewsDetailView.as_view(), name="news-detail"),
    path("news/list/", NewsView.as_view(), name="news"),
    path("news/all-list/", AllNewsView.as_view(), name="news-all"),
    # news crud
    path("category", CategoryView.as_view(), name="category-table"),
    path("category-create/", CategoryCreateView.as_view(), name="category-create"),
    path(
        "category-update/<int:pk>/",
        CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "category-delete/<int:pk>/",
        CategoryDeleteView.as_view(),
        name="category-delete",
    ),
    path("news-table/", NewsTableView.as_view(), name="news-table"),
    # add news/notice
    path("admin/add-news/", AddAdminNewsView.as_view(), name="add-anews"),
    # update news/notice
    path("admin/edit-news/<int:pk>/", EditAdminNewsView.as_view(), name="edit-anews"),
    ##########################
    path("news-delete/<int:pk>/", NewsDeleteView.as_view(), name="news-delete"),
    path(
        "recentactivity-detail/<int:pk>/",
        RecentActivityDetailView.as_view(),
        name="recentactivity-detail",
    ),
    path("recent-activity/list/", RecentActivityView.as_view(), name="recent-activity"),
     path("recent-activity/all-list/", AllRecentActivityView.as_view(), name="all-recent-activity"),
    # recent actvities crud
    path(
        "recent-activity/table/",
        RecentActivityTableView.as_view(),
        name="recentactivity-table",
    ),
    #####################recent activity #########
     path("recent-activity/add-recent-activity/", AddAdminRecentView.as_view(), name="add-arecent-activity"),
    # update news/notice
    path("recent-activity/edit-recent-activity/<int:pk>/", EditAdminRecentView.as_view(), name="edit-arecent-activity"),
    ##########################
    path(
        "recent-activity-delete/<int:pk>/",
        RecentActivityDeleteView.as_view(),
        name="recentactivity-delete",
    ),
    # dam knowledge
    path("damknowledge-salient-features/", DamKnowledgeSalientFeaturesView.as_view(), name="damknowledge"),
    path("pipeline/", PipeLineView.as_view(), name="pipeline"),
    path("name-of-dam/", NameOfDamView.as_view(), name="name-of-dam"),
    path("lake/", LakeView.as_view(), name="lake"),
    path("literature/", LiteratureView.as_view(), name="literatures"),
    # admin dam knowledge
    
    # administration
    path(
        "administration/login",
        AdministrationLoginView.as_view(),
        name="administration-login",
    ),
    path(
        "administration/darta-chalani", DartaChalaniView.as_view(), name="darta-chalani"
    ),
    path("administration/darta-list", DartaListView.as_view(), name="darta-list"),
    path("administration/darta-form", DartaFormView.as_view(), name="darta-form"),
    path("administration/chalani-list", ChalaniListView.as_view(), name="chalani-list"),
    path("administration/chalani-form", ChalaniFormView.as_view(), name="chalani-form"),
    path("darta/<int:pk>", DartaDetailView.as_view(), name="darta-detail"),
    path("darta/<int:pk>/update", DartaUpdateView.as_view(), name="darta-update"),
    path("darta/<int:pk>/delete", DartaDeleteView.as_view(), name="darta-delete"),
    path("chalani/<int:pk>", ChalaniDetailView.as_view(), name="chalani-detail"),
    path("chalani/<int:pk>/update", ChalaniUpdateView.as_view(), name="chalani-update"),
    path("chalani/<int:pk>/delete", ChalaniDeleteView.as_view(), name="chalani-delete"),
    path("administration/upload-file/", CUploadFileView.as_view(), name="c-upload-file"),
    path("administration/upload-file/add", CAddUploadFileView.as_view(), name="c-add-file"),
    path("administration/upload-file/edit/<int:pk>/", CEditUploadUpdateFileView.as_view(), name="c-edit-file"),
    path("administration/upload-file/delete/<int:pk>/", CEditUploadDeleteFileView.as_view(), name="c-delete-file"),

    # ========= Notice ========
    path("notice/", NoticeView.as_view(), name="notice"),
    path("notice/create/", NoticeCreateView.as_view(), name="notice-create"),
    path("notice/update/<int:pk>/", NoticeUpdateView.as_view(), name="notice-update"),
    path("notice/delete/<int:pk>/", NoticeDeleteView.as_view(), name="notice-delete"),
    path("admin/profile/", AdminProfileView.as_view(), name="admin-profile"),
    # message
    path("admin/messages/", MessageView.as_view(), name="admin-message"),
    path("messages/create/", MessageCreateView.as_view(), name="message-create"),
    path("messages/update/<int:pk>/", MessageUpdateView.as_view(), name="messages-update"),
    path("messages/delete/<int:pk>/", MessageDeleteView.as_view(), name="message-delete"),

    path("darta/search",DartaSearch.as_view(),name="darta-search")
    # for displying pdf
    #     path("admin/message/create/", MessageCreateView.as_view(), name="message-create"),
    #     path("admin/message/update/<int:pk>/", MessageUpdateView.as_view(), name="message-update"),
    #     path("admin/message/delete/<int:pk>/", MessageDeleteView.as_view(), name="message-delete"),
]

news/forms.py
from django import forms
from .models import News, RecentActivities, HomeNotice, Message
from bootstrap_modal_forms.forms import BSModalModelForm
from company.models import Darta, Chalani
from ckeditor.widgets import CKEditorWidget


class NewsForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = News
        exclude = ("views",)


class RecentActivitiesForm(forms.ModelForm):
    title = forms.CharField(required=True)
    content = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = RecentActivities
        exclude = ("views",)
        required_css_class = "required"


class HomeNoticeForm(forms.ModelForm):
    display = forms.CheckboxInput(attrs={"style": "width:500px;height:500px;margin-left:0px;padding-left:0px;"})

    class Meta:
        model = HomeNotice
        fields = ("image", "content", "files", "display")
       

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("name", "content", "designation", "image")


class DateInput(forms.DateInput):
    input_type = "date"


class DartaForm(forms.ModelForm):
    class Meta:
        model = Darta
        fields = ('darta_no', 'date', 'patra_no', 'cha_no', 'patra_received_date', 'sender', 'address', 'subject',
         'medium', 'remark', 'image', 'eng_date')
        widgets = {
                "image": forms.FileInput(attrs={'multiple': True}),
        }



class ChalaniForm(forms.ModelForm):

    class Meta:
        model = Chalani
        fields = ("chalani_no","date","patra_no","chalani_perform_date","sender","address","subject","remark","image")

        widgets = {
                "image": forms.FileInput(attrs={'multiple': True}),
        }

templates/news/news-detail.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %}News Detail{% endblock %}
<!-- You can use Open Graph tags to customize link previews.
Learn more: https://developers.facebook.com/docs/sharing/webmasters -->
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="article" />
<meta property="og:title" content="{{ news.title }}"/>
<meta property="og:description" content="{% if object.meta_description %}{{ object.meta_description }}{% else %}{{ news.content|safe|striptags|truncatewords:"20" }}{% endif %}"/>
<meta property="og:url" content="https://{{ request.get_host }}{% url 'detail_post_page' slug=object.slug %}"/>
{% if news.image %}
<meta property="og:image" content="https://dhapdam.gov.np/media/news/%25%20Y/%25%20m/%25%20d/notice.JPG"/>
{% endif %}

{% block script %}
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v12.0&appId=351136563294840&autoLogAppEvents=1" nonce="J8K8kivt"></script>
{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a href="{% url 'news:news' %}" class="link text-theme-light-blue">News</a> / <a href="{% url 'news:news-detail' news.pk %}" class="link text-theme-light-blue">News Detail</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="col-lg-12 mx-auto">
            <div class="newsblock">
                <div class="row mt-3">
                    <div class="col-lg-8">
                        <div class="contentBlock__detail">
                            <h5 class="content-title">{{news.title}}</h5>
                            <div class="entry__meta">
                                <span class="entry__meta--author f-bold">{{news.created_at|date:"d N Y"}}</span>
                            </div>
                            {% if news.image %}
                            <div class="blog-container my-2">
                                <img src="{{news.image.url}}" class="img-fluid">
                            </div>
                            {% endif %}
                            <div class="singleProduct-socialMediaNews">
                                <ul>
                                    
                                    <li><div class="fb-share-button" data-href="{{ request.get_full_path }}" data-layout="button_count" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A8000%2Fnews-detail%2F1%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div></li>
                                    {% comment %} <li><a href="" class="twi" target="_blank"><i class="fab fa-twitter"></i> <span>Twitter</span></a></li> {% endcomment %}
                                    {% comment %} <li><a href="" class="linkedin" target="_blank"><i class="fab fa-linkedin-in"></i> <span>Linkedin</span></a></li> {% endcomment %}
                                </ul>
                            </div>
                            <div class="entry__summary">
                                <p class="entry__summary---desc">{{news.content|safe}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="sidebarNews">
                            <div class="sidebarNews__heading">
                                <h6> Recent News</h6>
                            </div>
                            <div class="sidebarNews__content">
                                <ul class="newsCard__body---content">
                                    {% for recent in recent|slice:"8" %}
                                    <li>
                                        <div class="short-news">
                                            <a href="{% url 'news:news-detail' recent.pk %}">{{recent.title}}</a>
                                            <span class="d-block date">{{recent.created_at|date:"d N Y"}}</span>
                                        </div>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="text-center mt-2">
                                <a href="{% url 'news:news-all' %}" class="btn btn-secondary-theme w-50">View all</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/news/news.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- css -->
{% block static %}
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/custom-dataTables.css' %}"> {% endblock %}
<!-- title -->
{% block title %}News{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a
                    href="{% url 'news:news' %}" class="link text-theme-light-blue">News</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="col-lg-12 mx-auto">
            <h5 class="content-title">News/ Notice</h5>
            <div class="newsblock">
                <div class="row mt-3">
                    <div class="col-lg-8">
                        <div class="table-responsive bsa-responsive-table p-3">
                            <table id="table_dataframe" class="table content-table">
                                <thead>
                                    <tr>
                                        <th width="2%">S.No</th>
                                        <th width="15%">Title</th>
                                        <th width="32%">Content</th>
                                        <th width="12%">Image</th>
                                        <th width="12%">Category</th>
                                        <th width="8%">Published Date</th>
                                        <th width="8%">Task</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for news in news %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td class="content-table-title"><a href="{% url 'news:news-detail' news.id %}" class="dlink">{{news.title}}</a></td>
                                        <td class="content-line"><a href="{% url 'news:news-detail' news.id %}" class="dlink">{{news.content|safe}}</a></td>
                                        <td class="content-table-title">{% if news.image %}<a href="{{news.image.url}}" data-toggle="tooltip" data-placement="bottom" title="Open" target="_blank">{{news.image.url|slice:"36:"}}</a>{% else %} {% endif %}</td>
                                        <td class="content-line">{{news.category}}</td>
                                        <td><span class="badge bg-secondary f-13 font-weight-400">{{news.created_at|date:"d N Y"}}</span>
                                        </td>
                                        <td><a href="{% url 'news:news-detail' news.id %}" class="btn btn-secondary-theme btn-sm">View</a></td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="sidebarNews">
                            <div class="sidebarNews__heading">
                                <h6> Recent News</h6>
                            </div>
                            <div class="sidebarNews__content">
                                <ul class="newsCard__body---content">
                                    {% for recent in news|slice:"8" %}
                                    <li>
                                        <div class="short-news">
                                            <a href="{% url 'news:news-detail' recent.pk %}">{{recent.title}}</a>
                                            <span class="d-block date">{{recent.created_at|date:"d N Y"}}</span>
                                        </div>
                                    </li>
                                    {% endfor %}
                                </ul>
                                <div class="text-center mt-2">
                                    <a href="{% url 'news:news-all' %}" class="btn btn-secondary-theme w-50">View all</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %} {% block script %}
<script src="{% static 'admin/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#table_dataframe').DataTable({
            "autoWidth": false,
            "scrollX": true,
        });
    });
</script>
{% endblock %}

templates/news/recent-activity-detail.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %}Recent Activity Detail{% endblock %}
<!-- You can use Open Graph tags to customize link previews.
Learn more: https://developers.facebook.com/docs/sharing/webmasters -->
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="article" />
<meta property="og:title" content="{{ news.title }}"/>
<meta property="og:description" content="{% if object.meta_description %}{{ object.meta_description }}{% else %}{{ news.content|safe|striptags|truncatewords:"20" }}{% endif %}"/>
<meta property="og:url" content="https://{{ request.get_host }}{% url 'detail_post_page' slug=object.slug %}"/>
{% if news.image %}
<meta property="og:image" content="https://dhapdam.gov.np/media/news/%25%20Y/%25%20m/%25%20d/notice.JPG"/>
{% endif %}

{% block script %}
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v12.0&appId=351136563294840&autoLogAppEvents=1" nonce="J8K8kivt"></script>
{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a href="{% url 'news:recent-activity' %}" class="link text-theme-light-blue">Recent Activity</a> / <a href="{% url 'news:recentactivity-detail' activities.id %}" class="link text-theme-light-blue">Recent Activity Detail</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="col-lg-12 mx-auto">
            <div class="newsblock">
                <div class="row mt-3">
                    <div class="col-lg-8">
                        <div class="contentBlock__detail">
                            <h5 class="content-title">{{activities.title}}</h5>
                            <div class="entry__meta">
                                <span class="entry__meta--author f-bold">{{activities.created_at|date:"d N Y"}}</span>
                            </div>
                            <div class="blog-container my-2">
                                <img src="{{ activities.thumnail.url }}" class="img-fluid">
                            </div>
                            <div class="singleProduct-socialMediaNews">
                                <ul>
                                    <li><div class="fb-share-button" data-href="{{ request.get_full_path }}" data-layout="button_count" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A8000%2Fnews-detail%2F1%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div></li>
                                    {% comment %} <li><a href="" class="twi" target="_blank"><i class="fab fa-twitter"></i> <span>Twitter</span></a></li> {% endcomment %}
                                    {% comment %} <li><a href="" class="linkedin" target="_blank"><i class="fab fa-linkedin-in"></i> <span>Linkedin</span></a></li> {% endcomment %}
                                </ul>
                            </div>
                            <div class="entry__summary">
                                <p class="entry__summary---desc">{{activities.content|safe}}</p>
                                
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="sidebarNews">
                            <div class="sidebarNews__heading">
                                <h6> Recent Activities</h6>
                            </div>
                            <div class="sidebarNews__content">
                                {% for activity in recents|slice:"8" %}
                                <div class="popularPosts__Block">
                                    <div class="popularPosts__ImgBlock">
                                        <a href="{% url 'news:recentactivity-detail' activity.pk %}">
                                            {% if activity.thumnail %}<img src="{{activity.thumnail.url}}" class="img-fluid"></a>{% endif %}
                                    </div>
                                    <div class="popularPosts__contentBlock">
                                        <p class="popularPosts__Title"><a href="{% url 'news:recentactivity-detail' activity.pk %}">{{activity.title}}</a></p>
                                        <p class="popularPosts__contentDate"><i class="fa fa-clock-o"></i> {{activity.created_at|date:"d N Y"}}</p>
                                    </div>
                                </div>
                                {% endfor %}                                
                            </div>
                            <div class="text-center mt-2">
                                <a href="{% url 'news:all-recent-activity' %}" class="btn btn-secondary-theme w-50">View all</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}