bagmati/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from news.views import IndexView,MessageViewHome
from django.views.generic import TemplateView
from exceptionsapp.views import error_404,error_500,error_403,error_400

handler404 = 'exceptionsapp.views.error_404'
handler403 = 'exceptionsapp.views.error_403'
handler400 = 'exceptionsapp.views.error_400'
handler400 = 'exceptionsapp.views.error_500'


urlpatterns = [
    path("", include("contracts.urls")),
    path("user/", include("users.urls")),
    path("", include("news.urls")),
    path("", include("company.urls")),
    path("", include("construction.urls")),
    path("", include("dam.urls")),
    path("", include("damknowledge.urls")),

    # home
    path("", IndexView.as_view(), name="index"),
    path('message/<slug:slug>/', MessageViewHome.as_view(), name='message'),
    #list of apps
    path('admin/', admin.site.urls),
    path("", include('django.contrib.auth.urls')),
    #external package
    path('ckeditor/', include('ckeditor_uploader.urls')),


    
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contracts/urls.py
from django.urls import path
from .views import *

app_name = "contracts"

urlpatterns = [
    # get list of contract or single contract
    path("contracts/completed/", ContractCompletedView.as_view(), name="contract"),
    path("contracts/ongoing/", ContractOngoingView.as_view(), name="contract=ongoing"),
    path(
        "contracts/progress/", ContractProgressView.as_view(), name="contract-progress"
    ),
    path("contracts/<int:pk>", ContractCompletedView.as_view(), name="contract"),
    # ----------static url----------------
    path("contracts-ongoing/", ClientContractOngoingView.as_view(), name="c-ongoing"),
    path("contracts-completed/", ClientContractCompletedView.as_view(), name="c-completed"),
    path("contracts-progress/", ClientContractProgressView.as_view(), name="c-progress"),
    # ----------static url----------------
    # add and update of contract
    # path("contract/add", ContractCreateView.as_view(), name="contract-add"),
    path("contract/add", addContract, name="contract-add"),
    path("contract/<int:pk>", ContractDetailView.as_view(), name="contract-detail"),
    path("contract-list/", ContractListView.as_view(), name="contract-list"),
    path(
        "contract/update/<int:pk>", ContractUpdateView.as_view(), name="contract-update"
    ),
    path(
        "contract/delete/<int:pk>", ContractDeleteView.as_view(), name="contract-delete"
    ),
    # add and update of contract detail
    path("contract-detail/", ContractDetailList.as_view(), name="contract-detail-list"),
    path(
        "contract/<int:pk>",
        ContractDetailDetailView.as_view(),
        name="contract-detail-detail",
    ),
    path(
        "contract-detail/add", ContractDetailAdd.as_view(), name="contract-detail-add"
    ),
    path(
        "contract-detail/<int:pk>/update",
        ContractDetailUpdate.as_view(),
        name="contract-detail-update",
    ),
    path(
        "contract-detail/<int:pk>/delete",
        ContractDetailDelete.as_view(),
        name="contract-detail-delete",
    ),
    # crud for contract Feature
    path("contract-feature/", ContractFeatureList.as_view(), name="contract-feature"),
    path(
        "contract-feature/<int:pk>",
        ContractFeatureDetail.as_view(),
        name="contract-feature-detail",
    ),
    path(
        "contract-feature/add",
        ContractFeatureCreate.as_view(),
        name="contract-feature-add",
    ),
    path(
        "contract-feature/<int:pk>/update",
        ContractFeatureUpdate.as_view(),
        name="contract-feature-update",
    ),
    path(
        "contract-feature/<int:pk>/delete",
        ContractFeatureUpdate.as_view(),
        name="contract-feature-delete",
    ),
    # Crud for Contract Progress
    path("contract-progress/", ContractProgressGet.as_view(), name="contract-progress"),
    path(
        "contract-progress/add",
        ContractProgressAdd.as_view(),
        name="contract-progress-add",
    ),
    path(
        "contract-progress/<int:pk>/update",
        ContractProgressUpdate.as_view(),
        name="contract-progress-update",
    ),
    path(
        "contract-progress/<int:pk>/delete",
        ContractProgressDelete.as_view(),
        name="contract-progress-delete",
    ),
    # get url of different contract elements
    path(
        "contract/<int:pk>/intro",
        ContractIntroductionView.as_view(),
        name="contract-intro",
    ),
    path(
        "contract/<int:pk>/feature",
        ContractFeatureView.as_view(),
        name="contract-feature",
    ),
    path(
        "contract/<int:pk>/location",
        ContractLocationView.as_view(),
        name="contract-location",
    ),
    path(
        "contract/<int:pk>/design-quality",
        ContractDesignQualityView.as_view(),
        name="contract-design-quality",
    ),
    path(
        "contract/<int:pk>/env-aspects",
        ContractEnviromentalAspects.as_view(),
        name="contract-env-aspects",
    ),
    # for displaying purposes only
    path("dhap-dam/", DhapdamView.as_view(), name="dhap-dam"),
    path("dhap-features/", DhapFeaturesView.as_view(), name="dhap-features"),
    path("dhap-location/", DhapLocationView.as_view(), name="dhap-location"),
    path(
        "dhap-work-components/",
        DhapWorkComponentsView.as_view(),
        name="dhap-work-components",
    ),
    path(
        "dhap-work-components/<int:pk>/",
        DhapWorkComponentsDetailView.as_view(),
        name="dhap-work-components-detail",
    ),
    path("dhap-contract/", DhapContractDetailView.as_view(), name="dhap-contract"),
    path("dhap-design/", DhapDesignView.as_view(), name="dhap-design"),
    path(
        "dhap-environmental/",
        DhapEnvironmentalView.as_view(),
        name="dhap-environmental",
    ),
    path("dhap-maps/", DhapMapsView.as_view(), name="dhap-maps"),
]

dam/urls.py
from django.urls import path
from .views import *

app_name = "dam"

urlpatterns = [    
    #---------------------dhap-dam----------------------
    #introduction
    path("admin/dhapdam/introduction", DhapIntroView.as_view(), name="dadmin-intro"),
    path("admin/dhapdam/introduction/create/", AddDhapIntroCreateView.as_view(), name="add-dhap-intro"),
    path("admin/dhapdam/introduction/<int:pk>/update",
        DhapIntroUpdateView.as_view(),
        name="dhap-intro-update",
    ),
    path("admin/dhapdam/introduction/<int:pk>/delete",
        DhapIntroDeleteView.as_view(),
        name="dhap-intro-delete",
    ),

    #features
    path("admin/dhapdam/features", DhapFeaturesView.as_view(), name="dadmin-features"),
    # add featute
    path("admin/dhapdam/add-features", DhapAddFeatures.as_view(), name="dadmin-add-features"),
    #edit feature
    path("admin/dhapdam/edit-features/<int:pk>/", DhapEditFeatures.as_view(), name="dadmin-edit-features"),
    
    # path(
    #     "contract-progress/<int:pk>/delete",
    #     ContractProgressDelete.as_view(),
    #     name="contract-progress-delete",
    # ),

    #location  and accessibility
    path("admin/dhapdam/location", DhapLocationView.as_view(), name="dadmin-location"),
    path("admin/dhapdam/location/create/", DhapLocationCreateView.as_view(), name="add-dhap-location"),
    path("admin/dhapdam/location/<int:pk>/update",
        DhapLocationUpdateView.as_view(),
        name="dhap-location-update",
    ),
    # path("admin/dhapdam/location/<int:pk>/delete",
    #     DhapIntroDeleteView.as_view(),
    #     name="dhap-location-delete",
    # ),

    #work components
    path("admin/dhapdam/work-components", DhapWorkComponentView.as_view(), name="dadmin-work-components"),
    path("admin/dhapdam/work-components/create/", DhapWorkComponentCreateView.as_view(), name="add-dhap-work-components"),
    path("admin/dhapdam/work-components/<int:pk>/update",
        DhapWorkComponentUpdateView.as_view(),
        name="dhap-work-components-update",
    ),
    path("admin/dhapdam/work-components/<int:pk>/delete",
        DhapWorkComponentDeleteView.as_view(),
        name="dhapwork-components-delete",
    ),
    # sub work component
    path("admin/dhapdam/sub-work-components", DhapSubWorkComponentView.as_view(), name="dadmin-sub-subwork"),
    path("admin/dhapdam/sub-work-components/create/", DhapSubWorkComponentCreateView.as_view(), name="add-dhap-subwork-components"),
    path("admin/dhapdam/sub-work-components/<int:pk>/update",
        DhapSubWorkComponentUpdateView.as_view(),
        name="dhap-subwork-components-update",
    ),
    path("admin/dhapdam/sub-work-components/<int:pk>/delete",
        DhapSubWorkComponentDeleteView.as_view(),
        name="dhap-subwork-components-delete",
    ),
    # contract
    path("admin/dhapdam/contract-detail", DhapContractDetailView.as_view(), name="dadmin-contract-detail"),
     # add detail
    path("admin/dhapdam/add-detail", DhapAddContractDetail.as_view(), name="dadmin-add-detail"),
    #edit detail
    path("admin/dhapdam/edit-detail<int:pk>/", DhapEditContractDetail.as_view(), name="dadmin-edit-detail"),

    #design and quality aspects
    path("admin/dhapdam/design-quality", DhapDesignQualityView.as_view(), name="dadmin-design-quality"),
    path("admin/dhapdam/design-quality/add/", DhapDesignQualityCreateView.as_view(), name="add-dadmin-design-quality"),
    path("admin/dhapdam/design-quality/edit/<int:pk>/",
        DhapDesignQualityUpdateView.as_view(),
        name="dadmin-design-quality-update",
    ),



    # sub design
    path("admin/dhapdam/sub-design-quality", DhapSubDesignQualityView.as_view(), name="dadmin-sub-design-quality"),
    path("admin/dhapdam/sub-design-quality/create/", DhapSubDesignQualityCreateView.as_view(), name="add-dadmin-sub-design-quality"),
    path("admin/dhapdam/sub-design-quality/<int:pk>/update",
        DhapSubDesignQualityUpdateView.as_view(),
        name="dadmin-design-sub-quality-update",
    ),
    path("admin/dhapdam/sub-design-quality/<int:pk>/delete",
        DhapSubDesignQualityDeleteView.as_view(),
        name="dadmin-design-sub-quality-delete",
    ),
    # path("admin/dhapdam/list-design-quality", DhapListDesignQualityView.as_view(), name="dadmin-list-design"),

    path("admin/dhapdam/environmental-aspects", DhapEnvironmentalAspectsView.as_view(), name="dadmin-environmental-aspects"),
    path("admin/dhapdam/environmental-aspects/add/", DhapEnvironmentalAspectsCreateView.as_view(), name="add-dadmin-environmental-aspects"),
    path("admin/dhapdam/environmental-aspects/edit",
        DhapEnvironmentalAspectsUpdateView.as_view(),
        name="dadmin-environmental-aspects-update",
    ),
    #maps
    path("admin/dhapdam/maps", DhapMapsView.as_view(), name="dadmin-maps"),
    path("admin/dhapdam/maps/create/", MapsCreateView.as_view(), name="add-maps"),
    path("admin/dhapdam/maps/<int:pk>/update",
        MapsUpdateView.as_view(),
        name="maps-update",
    ),
    path("admin/dhapdam/maps/<int:pk>/delete",
        MapsDeleteView.as_view(),
        name="maps-delete",
    ),
    

    #-------------------nagmati dam-------------------
    #introduction
    path("admin/nagmati/introduction", NagmatiIntroView.as_view(), name="nadmin-intro"),
    path("admin/nagmati/introduction/create/", AddNagmatiIntroCreateView.as_view(), name="add-nagmati-intro"),
    path("admin/nagmati/introduction/<int:pk>/update",
        NagmatiIntroUpdateView.as_view(),
        name="nagmati-intro-update",
    ),
    #location
    path("admin/nagmati/location", NagmatiLocationView.as_view(), name="nadmin-location"),  
    path("admin/nagmati/location/create/", NagmatiLocationCreateView.as_view(), name="add-nagmati-location"),
    path("admin/nagmati/location/<int:pk>/update",
        NagmatiLocationUpdateView.as_view(),
        name="nagmati-location-update",
    ),
    #status of project
    path("admin/nagmati/project-status", NagmatiProjectStatusView.as_view(), name="nadmin-project-status"),
    path("admin/dhapdam/project-status/create/", NagmatiProjectStatusCreateView.as_view(), name="add-nadmin-project-status"),
    path("admin/dhapdam/project-status/<int:pk>/update",
        NagmatiProjectStatusUpdateView.as_view(),
        name="nadmin-project-statusupdate",
    ),
    #maps
    path("admin/nagmati/maps", NagmatiMapsView.as_view(), name="nadmin-maps"),
    path("admin/nagmati/maps/create/", NagmatiMapsCreateView.as_view(), name="add-nagmati-maps"),
    path("admin/nagmati/maps/<int:pk>/update",
        NagmatiMapsUpdateView.as_view(),
        name="maps-nagmati-update",
    ),
    path("admin/nagmati/maps/<int:pk>/delete",
        NagmatiMapsDeleteView.as_view(),
        name="maps-nagmati-delete",
    ),
    
    #salient features
    path("admin/nagmati/features", NagmatiFeaturesView.as_view(), name="nadmin-features"),
     # add featute
    path("admin/nagmati/add-features", NagmatiAddFeatures.as_view(), name="nadmin-add-features"),
    #edit feature
    path("admin/nagmati/edit-features/<int:pk>/", NagmatiEditFeatures.as_view(), name="nadmin-edit-features"),
    
    
]

templates/contract/completed-contract.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %}Contract{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a
                    href="{% url 'contracts:c-ongoing' %}" class="link text-theme-light-blue">Contract</a>/
                    <a class="link text-theme-light-blue">Completed</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">            
            <div class="row">
                <div class="col-md-8 col-sm-12">
                    <h5 class="content-title">Completed Contract</h5>
                    <form method="GET" class="contracts-form row row-cols-lg-auto g-3 align-items-center px-3 pt-3" data-year-url="{% url 'contracts:c-completed' %}">
                        <div class="col-12">
                            {% if com_contracts %}
                                <label for="bsa-label">Select Project </label>
                            {% endif %}
                        </div>
                        <div class="col-12">
                            {% if com_contracts %}

                            <select class="contracts-name bsa-custom-select form-select">
                                    {% for item in com_contracts %}
                                    <option value="{{ item.id }}"
                                        {% if item.project_name == completed_contract.project_name %}
                                        selected="selected" {% endif %}>{{ item.project_name }}
                                    </option>
                                    {% endfor %}
                            </select>
                            {% endif %}
                        </div>
                    </form>
                    <br>
                    <div class="contract-table">
                        <div class="contract-completed table-responsive bsa-responsive-table mt-0 border-0">
                            <!-- completed work  -->
                            <table class="table notranslate table-bordered bsa-table">
                                <tbody>                                                
                                    <tr>
                                        <th class="f-14" colspan="2"
                                            style="background-color: #CCC0DA; text-align: center;">
                                                {{completed_contract.project_name}}</th>
                                    </tr>
                                    <tr style="background-color: #FFC7CE">
                                        <th class="f-13">Contract ID</th>
                                        <td style="text-align: left;">{{completed_contract.contract_id}}
                                        </td>
                                    </tr>
                                    <tr style="background-color: #C6EFCE">
                                        <th class="f-13" width="25%">Project Name</th>
                                        <td style="text-align: left;">{{completed_contract.project_name}}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th class="f-13">Work Name</th>
                                        <td style="text-align: left;">{{completed_contract.work_name}}
                                        </td>
                                    </tr>
                                    
                                    <tr>
                                        <th class="f-13">Contract Name and address</th>
                                        <td style="text-align: left;">
                                            {{completed_contract.contractor_detail}}</td>
                                    </tr>
                                    <tr style="background-color: #FFC7CE">
                                        <th class="f-13">Date of agreement</th>
                                        <td style="text-align: left;">
                                            {{completed_contract.date_of_agreement}}</td>
                                    </tr>
                                    <tr style="background-color: #C6EFCE">
                                        <th class="f-13">Date of completion as agreement</th>
                                        <td style="text-align: left;">
                                            {{completed_contract.date_of_completion}}</td>
                                    </tr>
                                    <tr>
                                        <th class="f-13">Date of completion (Revised)</th>
                                        <td style="text-align: left;">
                                            {% if completed_contract.date_of_completion_revised %}{{completed_contract.date_of_completion_revised}}{% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th class="f-13">Amount of Agreement</th>
                                        <td style="text-align: left;">{{completed_contract.amount}}</td>
                                    </tr>
                                    <tr>
                                        <th class="f-13">Actual Expenditure</th>
                                        <td style="text-align: left;">
                                            {{completed_contract.actual_expenditure}}</td>
                                    </tr>
                                    <tr style="background-color: #C6EFCE">
                                        <th class="f-13">Current Project Status</th>
                                        <td style="text-align: left;">
                                            {{completed_contract.get_current_status_display}}</td>
                                    </tr>
                                    <tr>
                                        <th class="f-13">Contractor Libility Status</th>
                                        <td style="text-align: left;">
                                            {{completed_contract.get_contractor_liability_status_display}}
                                        </td>
                                    </tr>
                                    
                                    <tr style="background-color: #FFC7CE">
                                        <th class="f-13">Major works completed</th>
                                        <td style="text-align: left;">{{completed_contract.works_completed}}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-12">
                    <div class="sidebar-tab sidebar-sticky-top">
                        <h5 class="sidebar-tab__title">Contract</h5>
                        <ul class="sidebar-bar">
                            <li class="sidebar-bar__item"><a href="{% url 'contracts:c-ongoing' %}" class="sidebar-bar__item---link">Ongoing</a></li>
                            <li class="sidebar-bar__item active"><a href="{% url 'contracts:c-completed' %}" class="sidebar-bar__item---link active">Completed</a></li>
                            <li class="sidebar-bar__item"><a href="{% url 'contracts:c-progress' %}" class="sidebar-bar__item---link">Progress</a></li>
                        </ul>
                    </div>
                </div>
            </div>
    </div>
</section>
{% endblock %}
{% block script %}
<script>   
    $(".contracts-name").change(function () {
      var url = $(".contracts-form").attr("data-year-url");  // get the url of the `load_cities` view
      var contractId = $(this).val();  // get the selected country ID from the HTML input
      console.log("year id",contractId)
      console.log("url",url)

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'contractId': contractId       // add the country id to the GET parameters
        },
        success: function(data) {
             $('.contract-completed').html(jQuery(data).find('.contract-completed').html())
        }
      });

    });

</script>

{% endblock %}

templates/contract/progress-contract.html
{% extends '../layout/base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %}Contract{% endblock %}
<!-- content -->
{% block content %}
<section class="bsa-breadcrumb">
    <div class="container">
        <div class="breadcrumb mb-0">
            <span class="f-13"><a href="{% url 'index' %}" class="link text-theme-light-blue">Home</a> // <a
                    href="{% url 'contracts:c-ongoing' %}" class="link text-theme-light-blue">Contract</a>/
                    <a class="link text-theme-light-blue">Progress</a></span>
        </div>
    </div>
</section>
<section class="page about pad-top-bot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h5 class="content-title">Progress Contract</h5>
                <form method="GET" class="row row-cols-lg-auto g-3 align-items-center p-3" class="contracts-form" data-year-url="{% url 'contracts:contract' %}">
                    <div class="col-12">
                       {% if pro_contracts %}
                                <label for="bsa-label">Select Project </label>
                        {% endif %}
                    </div>
                    <div class="col-12">
                        {% if pro_contracts %}
                        <select class="bsa-custom-select form-select contracts-name">
                            {% for item in pro_contracts %}
                            <p>{{ item.contract.id }}</p>
                            <option value="{{ item.contract.id }}"
                                {% if item.contract.project_name == contract_progress.contract.project_name %} selected="selected"
                                {% endif %}>{{ completed_contract.contract.project_name }}{{ item.contract.project_name }}</option>
                            {% endfor %}
                        </select> {% endif %}
                    </div>
                </form>
                <div class="contract-table-progress table-responsive bsa-responsive-table mt-0 border-0 p-3 pt-0">
                    <table class="table notranslate table-bordered bsa-table">
                        <tbody>
                            <tr style="background-color: #CCC0DA;">
                                <td rowspan="2">S.N</td>
                                <td rowspan="2">Name of work </td>
                                <td rowspan="2">Contract ID</td>
                                <td rowspan="2">Name of Contractor</td>
                                <td rowspan="2">Contract Amount Rs</td>
                                <td rowspan="2">Date of Agreement</td>
                                <td rowspan="2">Date of completion as per Agreement</td>
                                <td rowspan="2">Revised Date of Completion</td>
                                <td rowspan="2">Time Extended based on Original schedule</td>
                                <td rowspan="2">Time Elapsed based on revised schedule %</td>
                                <td rowspan="2">Time Remaining based on extended schedule(Days)</td>
                                <td colspan="3">Financial Progress Rs</td>
                                <td colspan="2">Physical Progress</td>
                                <td rowspan="2">Progress Status</td>
                                <td rowspan="2">Remarks</td>
                            </tr>
                            <tr style="background-color: #CCC0DA">
                                <td>Amount</td>
                                <td>Percent</td>
                                <td>Last Payment Date</td>
                                <td>Percent</td>
                                <td>Date</td>
                            </tr>
                            {% if contract_progress %}
                            <tr>
                                <td>1</td>
                                <td>{{contract_progress.contract.work_name}}</td>
                                <td>{{contract_progress.contract.contract_id}} </td>
                                <td>{{contract_progress.contract.contractor_detail}} </td>
                                <td>{{contract_progress.contract.amount}} </td>
            
                                <td>{{contract_progress.contract.date_of_agreement}} </td>
                                <td>{{contract_progress.contract.date_of_completion}} </td>
                                <td>{% if contract_progress.contract.date_of_completion_revised %} {{contract_progress.contract.date_of_completion_revised}} {% endif %}
            
                                </td>
            
                                <!-- {% for key,value in contract_progress.date_of_completion_revised.items %}
                                        {% if value %}
                                            <td style="color: black;">{{value|last }}ram</td>
                                        {% else %}
                                            <td style="color: black;">None</td>
                                        {% endif %}
            
                                {% endfor %} -->
                                {% if contract_progress.time_extended_on_original_schedule > 100 %}
                                    <td style="background-color:#ffc7ce;color:black;">{{contract_progress.time_extended_on_original_schedule|floatformat:2 }}</td>
                                {% elif contract_progress.time_extended_on_original_schedule <= 100 %}
                                    <td style="background-color: #c9ffd5;color: #28a745;">{{contract_progress.time_extended_on_original_schedule|floatformat:2 }}</td>
                                {% endif %}
                                <!-- <td style="background-color: #c9ffd5;color: #28a745;">{{contract_progress.time_extended_on_original_schedule}}</td> -->
                                <td>{{contract_progress.time_elapsed_on_revise_schedule|floatformat:2}} </td>
                                <td>{{contract_progress.time_remaining_on_extended_schedule|floatformat:0}} </td>
                                <td>{{contract_progress.financial_progress_amount}}</td>
                                <td>{{contract_progress.financial_percent_amount|floatformat:0}}%</td>
                                <td>{{contract_progress.financial_progress_date}} </td>
                                <td>{{contract_progress.physical_percent_amount}}</td>
                                <td>{{contract_progress.physical_progress_date}}</td>
                                {% if contract_progress.physical_percent_amount < contract_progress.time_elapsed_on_revise_schedule %}
                                    <td style="background-color:#ffc7ce;color:#9c0006;">
                                    Laging behind
                                    </td>
            
                                {% else %}    
                                    <td style="background-color: #c9ffd5;color: #28a745;">Before Schedule</td> 
            
            
                                {% endif %}
                                <!-- <td style="background-color: #c9ffd5;color: #28a745;">{{contract_progress.progress_status}}</td> -->
                                <td>{{contract_progress.remarks}}</td>
                            </tr>
                            {% else %}
                            <tr>
                                <td colspan="18" style="text-align: center;">None</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sidebar-tab sidebar-sticky-top">
                    <h5 class="sidebar-tab__title">Contract</h5>
                    <ul class="sidebar-bar">
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:c-ongoing' %}" class="sidebar-bar__item---link">Ongoing</a></li>
                        <li class="sidebar-bar__item"><a href="{% url 'contracts:c-completed' %}" class="sidebar-bar__item---link">Completed</a></li>
                        <li class="sidebar-bar__item active"><a href="{% url 'contracts:c-progress' %}" class="sidebar-bar__item---link active">Progress</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %} {% block script %}
<script>
    //update contract progress
    $(".contracts-name").change(function() {
        var url = $(".contracts-form").attr("data-year-url"); // get the url of the `load_cities` view
        var contractId = $(this).val(); // get the selected country ID from the HTML input
        console.log("year id", contractId)
        console.log("url", url)

        $.ajax({ // initialize an AJAX request
            url: url, // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'contractId': contractId // add the country id to the GET parameters
            },
            success: function(data) {
                $('.contract-table-progress').html(jQuery(data).find('.contract-table-progress').html())
            }
        });

    });
</script>

{% endblock %}